config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, {
  	controllers: {
  		registrations: 'users/registrations',
  		sessions:      'users/sessions',
  		passwords:     'users/passwords'
  	}
  }

  resources :surveys do
    member do
      get :authorize
      get :process_authorization
    end
    collection do
      get :search
    end
  end

  get '/dashboard', to: 'dashboard#index'
  namespace :dashboard do
    resources :surveys do
      resources :authorized_surveyees_lists do

      end
      resources :questions do
        resources :answers
      end
      member do
        post :publish
      end
    end
  end

  namespace :elko do
  	resources :authorized_surveyees_lists do
      collection do
        post :toggle_status
      end
    end

  	resources :authorized_surveyees_lists do
    end
  	resources :features do
      collection do
        post :toggle_status
      end
    end

  	resources :answers do
      collection do
        post :toggle_status
      end
    end

  	resources :surveys do
      collection do
        post :toggle_status
      end
      resources :questions do
        collection do
          post :toggle_status
        end
      end
    end
  end
  
end

app/models/survey.rb
class Survey < ApplicationRecord

  ADDABLE     = false
  EDITABLE    = true
  VIEWABLE    = true
  PUBLISHABLE = true
  DELETEABLE  = true

  belongs_to :user
  has_many   :questions, dependent: :destroy
  has_one    :authorized_surveyees_list

  enum status: [:unpublished, :published]
  enum state: [:closed, :opened]

  validates_uniqueness_of :access_code
  validates_presence_of :title, :access_code

  def label
    "#{self.title}"
  end

  def authorized?
    self.authorized_surveyees_list.present?
  end

  def toggle_status
    if self.published?
      self.unpublished!
    else
      self.published!
    end
  end

end

app/controllers/dashboard/answers_controller.rb
class Dashboard::AnswersController < DashboardController

  def index

  end

  def destroy
    @survey = current_user.surveys.find(params[:survey_id])
    @answer = @survey.questions.find(params[:question_id]).answers.find(params[:id])

    if @answer.destroy
      redirect_back fallback_location: @survey
    else
      flash[:danger] = @answer.errors.full_messages.to_sentence
      redirect_back fallback_location: @survey
    end
  end

end

app/controllers/dashboard/authorized_surveyees_lists_controller.rb
class Dashboard::AuthorizedSurveyeesListsController < DashboardController

  def index

  end

  def new
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = AuthorizedSurveyeesList.new
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = AuthorizedSurveyeesList.new authorized_surveyees_list_params

    if @authorized_surveyee_list.save
      @survey.authorized_surveyees_list = @authorized_surveyee_list
      @survey.save
      flash[:success] = 'Successfully added the authorized surveyee list to your survey'
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @authorized_surveyee_list.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = @survey.authorized_surveyees_list
  end

  def update
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = @survey.authorized_surveyees_list

    if @authorized_surveyee_list.update authorized_surveyees_list_params
      flash[:success] = "Successfully updated this authorized surveyees list"
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @authorized_surveyee_list.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def show
    @survey = Survey.find(params[:survey_id])
    @surveyee_list = @survey.authorized_surveyees_list
  end

  def destroy
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = @survey.authorized_surveyees_list

    if @authorized_surveyee_list.destroy
      flash[:success] = "Successfully deleted the authorized surveyees list"
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @authorized_surveyee_list.errors.full_messages.to_sentence
      redirect_to dashboard_survey_path @survey
    end
  end

  private
  def authorized_surveyees_list_params
    params.require(:authorized_surveyees_list).permit(:identification_type, :list)
  end

end

app/controllers/dashboard/questions_controller.rb
class Dashboard::QuestionsController < DashboardController

  def new
    @survey = current_user.surveys.find(params[:survey_id])
    @question = Question.new
    @question.answers.build
  end

  def create
    @survey = current_user.surveys.find(params[:survey_id])
    @question = Question.new question_params

    if @question.save 
      @survey.questions << @question
      flash[:success] = "Successfully added question"
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @question.errors.full_messages.to_sentence
      render :edit
    end
  end

  def edit
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @question.answers.build
  end

  def update
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])

    if @question.update question_params 
      flash[:success] = 'Successfully updated question'
      redirect_to dashboard_survey_path @survey
    else
      flash[:error] = @question.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @question = current_user.surveys.find(params[:survey_id]).questions.find(params[:id])

    if @question.destroy
      flash[:success] = 'Successfully deleted question'
      redirect_back fallback_location: dashboard_surveys_path
    else
      flash[:danger] = @question.errors.full_messages.to_sentence
      redirect_back fallback_location: dashboard_surveys_path   
    end
  end

  private 

  def question_params
    params.require(:question).permit(:title, answers_attributes: Answer.attribute_names.map(&:to_sym).push(:_destroy))
  end

end

app/controllers/dashboard/surveys_controller.rb
class Dashboard::SurveysController < DashboardController

	def index
		@surveys = current_user.surveys
	end

	def new
		@survey = Survey.new
	end

	def create
		@survey = Survey.new survey_params
		current_user.surveys << @survey
		if @survey.save
			flash[:success] = "You successfully created a new Survey!"
			redirect_to dashboard_surveys_path
		else
			flash[:danger] = @survey.errors.full_messages.to_sentence
			redirect_to dashboard_surveys_path
		end
	end

	def show
		@survey = current_user.surveys.find(params[:id])
		@questions = @survey.questions
	end

	def destroy
		@survey = current_user.surveys.find(params[:id])

		if @survey.destroy
			flash[:success] = "We successfully deleted your survey!"
			redirect_back fallback_location: dashboard_surveys_path
		else
			flash[:danger] = @survey.errors.full_messages.to_sentence
			redirect_back fallback_location: dashboard_surveys_path
		end
	end

  def publish
		@survey = current_user.surveys.find(params[:id])
		@survey.toggle_status
		flash[:success] = 'Successfully published your survey!'
		redirect_back fallback_location: @survey
	end

	private 

	def survey_params
		params.require(:survey).permit(:title, :description, :access_code)
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :authenticate_user!

	def index
		
	end

end

app/controllers/elko/surveys_controller.rb
class Elko::SurveysController < Elko::BlocksController
  before_action :authenticate_elko_user!

  def block_model
    Survey
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def show
    @survey = Survey.find(params[:id])

    if @survey.authorized?
      if (!params[:identification].present?) || (!@survey.authorized_surveyees_list.includes?(params[:identification]))
        redirect_to authorize_survey_path(@survey)
        return
      end
    end

    if params[:processable].present? && params[:processable] == "true"
      params.keys.each do |key|
        @question = @survey.questions.find_by_title(key)
        if @question
          @answer = @question.answers.find_by_title(params[key])
          if @answer
            @answer.number_of_times_chosen = @answer.number_of_times_chosen + 1
            @answer.save
          end
        end
      end

      if @survey.authorized?
        @new_array_list = @survey.authorized_surveyees_list.list.split(" ").delete_if { |a| a == params[:identification]}
        @survey.authorized_surveyees_list.list = @new_array_list.join(" ")
        @survey.authorized_surveyees_list.save
      end

      redirect_to root_path
    end
  end

  def search
    @search_query = SurveyQuery.new survey_query_params

    @survey = Survey.published.find_by_access_code(@search_query.query)
    if @survey
      redirect_to @survey
    else
      flash[:danger] = 'Whoops! We couldn\'t find a survey with that access code! :('
      redirect_back fallback_location: root_path
    end
  end

  def authorize
    @survey = Survey.find(params[:id])
    @authorized_entry = AuthorizedEntry.new
  end

  def process_authorization
    @survey = Survey.find(params[:id])
    @authorized_entry = AuthorizedEntry.new authorized_entry_params

    if @survey.authorized_surveyees_list.includes?(@authorized_entry.identification)
      redirect_to survey_path(@survey, identification: @authorized_entry.identification)
    else
      redirect_to root_path
    end
  end

  private
  def authorized_entry_params
    params.require(:authorized_entry).permit(:identification)
  end

  def survey_query_params
    params.require(:survey_query).permit(:query)
  end

end

app/views/dashboard/surveys/index.html.erb
<div>
 	<h2 class='float-left mt-2'>Surveys</h2>
	<%= link_to fa_icon('plus', text: 'Create a New Survey'), new_dashboard_survey_path, class: 'btn btn-md btn-primary float-right mt-2' %>
	<div class='fix-float'></div>
</div>

<hr> 

<% if @surveys.count > 0 %>
	<h3>Here are all your surveys</h3>
	<table class="table table-bordered table-hover">
	  <thead>
	    <tr>
	      <th scope="col">Title</th>
	      <th scope="col">Status</th>
	      <th scope="col">State</th>
				<th scope="col">Actions</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% @surveys.each do |survey| %>
	      <tr>
	        <td><%= survey.title %></td>
	        <td><%= survey.status.titleize %></td>
	        <td><%= survey.state.titleize %></td>
					<td>
						<%= link_to fa_icon('trash', text: 'Destroy'), dashboard_survey_path(survey), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-primary'%>
						<%= link_to fa_icon('eye', text: 'View'), dashboard_survey_path(survey),class: 'btn btn-sm btn-primary'%>
					</td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
<% else %>
  <h2>You have no surveys. :(</h2>
<% end %>

app/views/dashboard/surveys/new.html.erb
<h2>Enter the name of your survey</h2>

<%= simple_form_for @survey, url: dashboard_surveys_path do |f| %>

	<div class='form-group'>
		<%= f.input :title, input_html: { class: 'form-control' } %>
	</div>

	<div class='form-group'>
		<%= f.input :description, input_html: { class: 'form-control' } %>
	</div>

	<div class='form-group'>
		<%= f.input :access_code, 
			placeholder: 'This is the code surveyees will enter to access your survey',
			input_html: { class: 'form-control' } 
		%>
	</div>

		<%= f.submit class: 'btn btn-md btn-primary' %>

<% end %>

app/views/dashboard/surveys/show.html.erb
<h2 class='mt-3 float-left'><%= @survey.title.titleize %></h2>
<div class='float-right mt-3'>
  <% if @survey.published? %>
    <%= link_to fa_icon('upload', text: 'Unpublish'), publish_dashboard_survey_path(@survey), method: :post, class: 'btn btn-primary btn-md' %>
  <% else %>
    <%= link_to fa_icon('upload', text: 'Publish'), publish_dashboard_survey_path(@survey), method: :post, class: 'btn btn-primary btn-md' %>
  <% end  %>
  <%= link_to fa_icon('plus', text: 'Add A Question'), new_dashboard_survey_question_path(@survey), class: 'btn btn-primary btn-md' %>

  <% if @survey.authorized_surveyees_list.present? %>
    <%= link_to fa_icon('eye', text: 'View Surveyee List'), dashboard_survey_authorized_surveyees_list_path(@survey, @survey.authorized_surveyees_list), class: 'btn btn-primary btn-md' %>
  <% else %>
    <%= link_to fa_icon('plus', text: 'Add a Surveyee List'), new_dashboard_survey_authorized_surveyees_list_path(@survey), class: 'btn btn-primary btn-md' %>
  <% end  %>
</div>

<hr class='fix-float'>

<% if !@survey.published? %>
  <strong>***Note that you have not published your survey. Users will not be able to access it unless it is published</strong>
<% end %>
<p>This is your survey code: <strong><%= @survey.access_code %></strong></p>

<% @questions.each do |question| %>

  <% if question.total_answers_chosen > 0 %>
    <ul class="list-group">
      <li class="list-group-item">
        <strong><%= question.title %></strong>
        <div class="float-right">
          <%= link_to 'Delete', dashboard_survey_question_path(@survey, question), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to 'Edit', edit_dashboard_survey_question_path(@survey, question) %>
        </div>
      </li>
    </ul>
    <div class="row">
      <% @data_array = Array.new %>
      <div class="col-md-6 vertical-align">
        <div class="card text-center">
          <ul class="list-group list-group-flush">
            <% question.answers.each do |answer| %>
              <div class="list-group-item">
                <div class="float-left">
                  <strong><%= answer.title%></strong> | chosen: <%= answer.number_of_times_chosen %> time(s) | <%= (answer.get_percentage_chosen(question) * 100).to_i %>%
                </div>
                <div class="float-right">
                  <%= link_to 'Delete', dashboard_survey_question_answer_path(@survey, question, answer), method: :delete, data: { confirm: "Are you sure?" } %>
                </div>
              </div>
              <% @data_array << [answer.title, (answer.get_percentage_chosen(question)) ] %>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-md-6">
        <%= pie_chart @data_array %><br>
      </div>
    </div>
  <% else %>
    <div>
      <%= question.title %> | <strong>No one has submitted any answers for this question!</strong>
      <%= link_to 'Delete', dashboard_survey_question_path(@survey, question), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Edit', edit_dashboard_survey_question_path(@survey, question) %>
    </div>
    <ul>
      <% question.answers.each do |answer| %>
        <li><%= answer.title %> | <%= link_to "Delete", dashboard_survey_question_answer_path(@survey, question, answer), method: :delete, data: { confirmation: "Are you sure?" } %></li>
      <% end  %>
    </ul>
  <% end %>
<% end %>