config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, {
  	controllers: {
  		registrations: 'users/registrations',
  		sessions:      'users/sessions',
  		passwords:     'users/passwords'
  	}
  }

  resources :surveys do
    member do
      get :authorize
      get :process_authorization
    end
    collection do
      get :search
    end
  end

  get '/dashboard', to: 'dashboard#index'
  namespace :dashboard do
    resources :surveys do
      resources :authorized_surveyees_lists do

      end
      resources :questions do
        resources :answers
      end
      member do
        post :publish
      end
    end
  end

  namespace :elko do
  	resources :authorized_surveyees_lists do
      collection do
        post :toggle_status
      end
    end

  	resources :authorized_surveyees_lists do
    end
  	resources :features do
      collection do
        post :toggle_status
      end
    end

  	resources :answers do
      collection do
        post :toggle_status
      end
    end

  	resources :surveys do
      collection do
        post :toggle_status
      end
      resources :questions do
        collection do
          post :toggle_status
        end
      end
    end
  end
  
end

app/models/question.rb
class Question < ApplicationRecord

  ADDABLE     = true
  EDITABLE    = true
  VIEWABLE    = true
  PUBLISHABLE = true
  DELETEABLE  = true

  belongs_to :survey, optional: true
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: proc { |att| att['title'].blank? }

  def label
    "#{title}"
  end

  def total_answers_chosen
    total = 0
    self.answers.each do |answer|
      total = total + answer.number_of_times_chosen
    end
    total
  end

end

app/controllers/dashboard/answers_controller.rb
class Dashboard::AnswersController < DashboardController

  def index

  end

  def destroy
    @survey = current_user.surveys.find(params[:survey_id])
    @answer = @survey.questions.find(params[:question_id]).answers.find(params[:id])

    if @answer.destroy
      redirect_back fallback_location: @survey
    else
      flash[:danger] = @answer.errors.full_messages.to_sentence
      redirect_back fallback_location: @survey
    end
  end

end

app/controllers/dashboard/authorized_surveyees_lists_controller.rb
class Dashboard::AuthorizedSurveyeesListsController < DashboardController

  def index

  end

  def new
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = AuthorizedSurveyeesList.new
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = AuthorizedSurveyeesList.new authorized_surveyees_list_params

    if @authorized_surveyee_list.save
      @survey.authorized_surveyees_list = @authorized_surveyee_list
      @survey.save
      flash[:success] = 'Successfully added the authorized surveyee list to your survey'
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @authorized_surveyee_list.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = @survey.authorized_surveyees_list
  end

  def update
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = @survey.authorized_surveyees_list

    if @authorized_surveyee_list.update authorized_surveyees_list_params
      flash[:success] = "Successfully updated this authorized surveyees list"
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @authorized_surveyee_list.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def show
    @survey = Survey.find(params[:survey_id])
    @surveyee_list = @survey.authorized_surveyees_list
  end

  def destroy
    @survey = Survey.find(params[:survey_id])
    @authorized_surveyee_list = @survey.authorized_surveyees_list

    if @authorized_surveyee_list.destroy
      flash[:success] = "Successfully deleted the authorized surveyees list"
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @authorized_surveyee_list.errors.full_messages.to_sentence
      redirect_to dashboard_survey_path @survey
    end
  end

  private
  def authorized_surveyees_list_params
    params.require(:authorized_surveyees_list).permit(:identification_type, :list)
  end

end

app/controllers/dashboard/questions_controller.rb
class Dashboard::QuestionsController < DashboardController

  def new
    @survey = current_user.surveys.find(params[:survey_id])
    @question = Question.new
    @question.answers.build
  end

  def create
    @survey = current_user.surveys.find(params[:survey_id])
    @question = Question.new question_params

    if @question.save 
      @survey.questions << @question
      flash[:success] = "Successfully added question"
      redirect_to dashboard_survey_path @survey
    else
      flash[:danger] = @question.errors.full_messages.to_sentence
      render :edit
    end
  end

  def edit
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @question.answers.build
  end

  def update
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])

    if @question.update question_params 
      flash[:success] = 'Successfully updated question'
      redirect_to dashboard_survey_path @survey
    else
      flash[:error] = @question.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @question = current_user.surveys.find(params[:survey_id]).questions.find(params[:id])

    if @question.destroy
      flash[:success] = 'Successfully deleted question'
      redirect_back fallback_location: dashboard_surveys_path
    else
      flash[:danger] = @question.errors.full_messages.to_sentence
      redirect_back fallback_location: dashboard_surveys_path   
    end
  end

  private 

  def question_params
    params.require(:question).permit(:title, answers_attributes: Answer.attribute_names.map(&:to_sym).push(:_destroy))
  end

end

app/controllers/dashboard/surveys_controller.rb
class Dashboard::SurveysController < DashboardController

	def index
		@surveys = current_user.surveys
	end

	def new
		@survey = Survey.new
	end

	def create
		@survey = Survey.new survey_params
		current_user.surveys << @survey
		if @survey.save
			flash[:success] = "You successfully created a new Survey!"
			redirect_to dashboard_surveys_path
		else
			flash[:danger] = @survey.errors.full_messages.to_sentence
			redirect_to dashboard_surveys_path
		end
	end

	def show
		@survey = current_user.surveys.find(params[:id])
		@questions = @survey.questions
	end

	def destroy
		@survey = current_user.surveys.find(params[:id])

		if @survey.destroy
			flash[:success] = "We successfully deleted your survey!"
			redirect_back fallback_location: dashboard_surveys_path
		else
			flash[:danger] = @survey.errors.full_messages.to_sentence
			redirect_back fallback_location: dashboard_surveys_path
		end
	end

  def publish
		@survey = current_user.surveys.find(params[:id])
		@survey.toggle_status
		flash[:success] = 'Successfully published your survey!'
		redirect_back fallback_location: @survey
	end

	private 

	def survey_params
		params.require(:survey).permit(:title, :description, :access_code)
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :authenticate_user!

	def index
		
	end

end

app/controllers/elko/questions_controller.rb
class Elko::QuestionsController < Elko::BlocksController
  before_action :authenticate_elko_user!

  def block_model
    Question
  end

end

app/views/dashboard/questions/_answer.html.erb
<tr>
  <td>
    <%= f.input_field :_destroy, as: :hidden %>
    <%= link_to link_to 'Delete', '#', class: 'remove_record' %>
  </td>
  <td><%= f.input :title %></td> 
</tr>

app/views/dashboard/questions/edit.html.erb
<h2 class='mt-3'><%= @survey.title.titleize %></h2>
<hr>

<h3>Edit A Question</h3>
<small>You can delete answer choices on the survey page.</small>

<%= simple_form_for @question, url: dashboard_survey_question_path(@survey, @question) do |f| %>
  
  <div class='form-group'>
    <%= f.input :title, 
      placeholder: 'Enter Question Title Here ...', 
      label: 'Question title',
      input_html: { class: 'form-control' } %>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Answer Title</th>
      </tr>
    </thead>
    <tbody class='fields'>
      <%= f.simple_fields_for :answers do |builder| %>
        <%= render 'answer', f: builder %>
      <% end %>
    </tbody>
  </table>

  <div class='form-actions'>
  <%= f.submit class: 'btn btn-primary btn-md'%>
  <%= link_to_add_row('Add Answer', f, :answers, class: 'btn btn-primary') %>
  </div>

<% end %>

app/views/dashboard/questions/new.html.erb
<h2 class='mt-3'><%= @survey.title.titleize %></h2>
<hr>

<h3>Add A Question</h3>

<%= simple_form_for @question, url: dashboard_survey_questions_path do |f| %>
  
  <div class='form-group'>
    <%= f.input :title, 
      placeholder: 'Enter Question Title Here ...', 
      label: 'Question title',
      input_html: { class: 'form-control' } %>
  </div>
  
  <table class='table'>
    <thead>
      <tr>
        <th></th>
        <th>Answer Title</th>
      </tr>
    </thead>
    <tbody class='fields'>
      <%= f.simple_fields_for :answers do |builder| %>
        <%= render 'answer', f: builder %>
      <% end %>
    </tbody>
  </table>

  <div class='form-actions'>
  <%= f.submit class: 'btn btn-primary btn-md'%>
  <%= link_to_add_row('Add Answer', f, :answers, class: 'btn btn-primary') %>
  </div>

<% end %>